
=============================================
Testing the function multiplies two matrices
101-lazy_matrix_mul

=============================================

::
    >>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

#test_1
>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
array([[ 7, 10],
       [15, 22]])

#test_2
>>> lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]])
array([[13, 16]])

#test_3
>>> lazy_matrix_mul([[1, 2, 3]], [[1, 2, 3], [4,5, 6], [7, 8, 9]])
array([[30, 36, 42]])

#test_4
>>> lazy_matrix_mul([[1, 2, 3], [4, 5, 6]], [[1], [2], [3]])
array([[14],
       [32]])

#test_5
>>> lazy_matrix_mul([[1, 2], [3, 4]], [[5, 6], [7, 8]])
array([[19, 22],
       [43, 50]])

#test_6
>>> lazy_matrix_mul(" Holberton", [[5, 6], [7, 8]])
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

#test_7
>>> lazy_matrix_mul([[5, 6], [7, 8]], "Holberton")
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

#test_8
>>> lazy_matrix_mul([[]], [[5, 6], [7, 8]])
Traceback (most recent call last):
ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

#test_9
>>> lazy_matrix_mul([[5, 6], [7, 8]], [[]])
Traceback (most recent call last):
ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

#test_10
>>> lazy_matrix_mul([[5, "6"], [7, 8]], [[5, 6], [7, 8]])
Traceback (most recent call last):
TypeError: invalid data type for einsum


#test_11
>>> lazy_matrix_mul([[5, 6], [7, 8]], [[5, "6"], [7, 8]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

#test_12
>>> lazy_matrix_mul([[5, 6, 10], [7, 8]], [[5, 6], [7, 8]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.


#test_13
>>> lazy_matrix_mul([[5, 6], [7, 8]], [[5, 6, 1], [7, 8]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

#test_14
>>> lazy_matrix_mul([[1, 2, 3], [3, 4, 5]], [[1, 2], [3, 4]])
Traceback (most recent call last):
ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


#test_15
>>> lazy_matrix_mul([1])
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

#test_16
>>> lazy_matrix_mul()
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

#test_17
>>> lazy_matrix_mul([[1, 2], [3, 4], [3, 4]] [[5, 6, 1], [7, 8, 2]])
Traceback (most recent call last):
TypeError: list indices must be integers, not tuple
